### ISSUE TITLE
当开启booknote显示无法加载此插件！

### ISSUE THREAD

**Issue by Xrebirth** [chenghongyao/obsidian-booknote-plugin#11]
操作系统：Window 11
操作系统版本：22000.469
obsidian版本：V0.13.23
弹窗显示：Failed to load plugin obsidian booknote-plugin
控制台报错：Plugin failure: obsidian-booknote-plugin Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\tes\test\.obsidian\plugins\obsidian-booknote-plugin-master\main.js'
我重新创建一个库然后什么插件不安装也开启不了。

**Comment by chenghongyao** [comment]
0.2.4我只放了一个main.js，只用这一个是不够的，可以用0.2.3里的manifest.json和styles.css，
