### ISSUE TITLE
标注链接参数错误

### ISSUE THREAD

**Issue by pophoo** [chenghongyao/obsidian-booknote-plugin#13]
有些PDF，点击链接，无法跳回PDF，显示标注链接参数错误。
<img width="386" alt="无标题" src="https://user-images.githubusercontent.com/4638577/155648826-e3b9e569-e8cc-407e-bf57-ac29c4cc7438.png">

**Comment by chenghongyao** [comment]
链接看一下，检查一下是不是`book=null`了，用最新的config.js试试

**Comment by pophoo** [comment]
换成webviewer-0.2.2.zip就可以了，感谢大神！
