### ISSUE TITLE
希望能学习你的代码，写几个太微插件

### ISSUE THREAD

**Issue by linonetwo** [chenghongyao/obsidian-booknote-plugin#14]
你好，我是 [https://github.com/tiddly-gittly/TidGi-Desktop](https://github.com/tiddly-gittly/TidGi-Desktop) 的作者，我希望把太微打造成最好用的从核心到插件完全低约束协议开源的渐进阅读工具，感觉 pdf 阅读是不可或缺的一部分，希望能借鉴一下你的代码，写一个 MIT 协议的太微插件增强其 PDF 渐进阅读能力。

所以希望你能明确一下这个仓库的代码开源协议~

**Comment by chenghongyao** [comment]
你好，这个插件代码本身比较简单，说学习言重了，但是版权问题也是我的主要问题。

我的阅读器使用的是pdftron的[webviewer](https://github.com/PDFTron/webviewer-ui)，这是一个商业SDK，暂时用它做了初步尝试，所以目前还不能确定这个项目可以使用何种开源协议。

我目前正在重构代码，也在尝试使用pdfjs实现pdf阅读器，希望能代替webviewer。

**Comment by linonetwo** [comment]
了解了，这个 SDK 功能挺多的，用 pdfjs 写那么多标注工具估计有点难，类似于 [https://github.com/burtonator/polar-bookshelf](https://github.com/burtonator/polar-bookshelf) 里那样的了。

而且我感觉没有商业用途的话应该先用着也没事？

**Comment by chenghongyao** [comment]
请教了一些人，似乎还是有风险的。

此外这个 SDK 也有一些难以解决的问题，比如启动过慢，没有授权的话阅读和导出都有水印，还发现有些 pdf 打不开（pdf.js 却可以），还有作为 obsidian 的插件也有棘手的跨域问题。不知道你的软件环境怎么样，但是这几个是我难以接受的问题。

**Comment by linonetwo** [comment]
我的环境是开源可控的 Electron 环境，可以自定义浏览器参数解决跨域问题，不过别的问题也不大好，可能还是得想办法找个社区维护开源免费的 pdfjs 框架吧。
