### ISSUE TITLE
zotero导入这个我不太懂，有没有更详细的解释呢？

### ISSUE THREAD

**Issue by zhl111** [chenghongyao/obsidian-booknote-plugin#15]
![image](https://user-images.githubusercontent.com/29135984/156608141-a91d971b-2c9d-4d07-931a-e7fb59b6d5fc.png)
我看到之前装过的插件citation有路径，booknote这个路径如何设置？
![image](https://user-images.githubusercontent.com/29135984/156608705-48741421-54f0-497b-b94e-f9d6019c6d61.png)

**Comment by chenghongyao** [comment]
这个不太稳定，建议暂时不要用了
