### ISSUE TITLE
很好用，真的非常好用，但是有些疑问

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [chenghongyao/obsidian-booknote-plugin#18]
1.说这话好像不太合适，如果开发者不开发了，原先标注的会不会消失
2.请问webview我在网上查说是付费的，如果开发者不续费，是不是这个插件就不能用了
纯小白，无恶意，仅仅是考虑笔记的安全，如果webview是付费的，开发者可以让大家付费支持，这样能长久下去，真的我超级超级喜欢这个插件

**Comment by shoudeyunkaijianyueming** [comment]
亦或者说现在这个版本我能一直用，不用担心某一天不能用了

**Comment by chenghongyao** [comment]
- 这个阅读器本来就没有付费，要不然也不会有水印，所以不存在不续费的问题；
- 最近有点忙，暂时停止开发。但是后面标注会加上导出的功能(仅限pdf，并且是简单的标注类型，如下划线、高亮、自由文本，区域高亮等，手写不确定能不能导出)；
- 这个 webviewer 价格很高，我个人没有办法付费，也没有能力和精力商业化，正在尝试使用 pdfjs 替代。

**Comment by shoudeyunkaijianyueming** [comment]
那现在我使用这个版本的插件，我不更新我可以永久用下去（有水印没问题的）

**Comment by chenghongyao** [comment]
> 那现在我使用这个版本的插件，我不更新我可以永久用下去（有水印没问题的）

应该是可以的

**Comment by shoudeyunkaijianyueming** [comment]
谢谢大佬，不着急更新，现在就够我用了
