### ISSUE TITLE
当前文件不支持截图

### ISSUE THREAD

**Issue by wizardxxm** [chenghongyao/obsidian-booknote-plugin#19]
截图标注在复制回链时提示：当前文件不支持截图，我打开的是PDF文件. 配置为远程服务或本地服务都不能截图。
首先默认的远程服务器https://relaxed-torvalds-5a5c77.netlify.app 已知失效，其次，win10安装webview2 runtime后，
解压插件带的webviewer并配置，但仍不能截图。尝试在浏览器打开localhost:1448提示"Error getting the file: Error: EISDIR: illegal operation on a directory, read."
是我webview安装的不对么
我OB是win版0.13.33，插件版本0.2.4 , webview2是从这里下载的:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/?msclkid=ace06bd3ab5311ec97f427053694464d

**Comment by chenghongyao** [comment]
不用下载webview吧，控制台有什么错误吗

**Comment by wizardxxm** [comment]
控制台输出：
2022-03-28 06:16:08 Loading updated app package C:\Users\xxx\AppData\Roaming\obsidian\obsidian-0.13.33.asar
2022-03-28 06:16:08 Checking for update using Github
2022-03-28 06:16:08 Success.
2022-03-28 06:16:08 Latest version is 0.13.33
2022-03-28 06:16:08 App is up to date.
(node:1088) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Obsidian --trace-deprecation ...` to show where the warning was created)

但我在另外两台电脑上就可以截图，一台win10，配置为使用本地服务。另一台ubuntu，配置为使用远程服务。

**Comment by chenghongyao** [comment]
这错误应该不是这插件发出来的，如果别的电脑可以用，那可能就是系统问题了，这个我很难确定。
