### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by linfengtongxue70** [chenghongyao/obsidian-booknote-plugin#2]
作者大大好，请问能否考虑以下两个建议呢：
1，pdf截图保存至指定文件夹，让文件夹清清爽爽。当然，如果截图的命名格式为文件名+日期就更好了，方便回忆。
2，引用加入回链，因为有些pdf ocr识别的太差了，可能需要回到PDF看原文。

**Comment by chenghongyao** [comment]
嗯嗯，后面会做的。

**Comment by chenghongyao** [comment]
已经完成。
