### ISSUE TITLE
webview跨域问题和booknote复制问题

### ISSUE THREAD

**Issue by windwindwa** [chenghongyao/obsidian-booknote-plugin#20]

**Comment by windwindwa** [comment]
### 配置与插件版本：
mac mini M1，obsidian v0.14.2, webview是文档中提供的新版（截止2022.3.31日）https://kknwfe6755.feishu.cn/docs/doccnBfbtETItLHMmbDBGBRdPrh
booknote-0.2.4-beta
### 问题描述
- 通过booknote打开pdf文件，控制台报错webview跨域错误。但可以使用
- 通过高亮涂抹文字，没有自动粘贴到右侧已打开文档中，手动复制，可以使用，但控制台报错。

### 报错截图如下： 

![image](https://user-images.githubusercontent.com/48432322/160996563-ea87d541-21c7-4129-bae4-cec8a277b431.png)

**Comment by windwindwa** [comment]
### 补充一下，跳转失效了
api调不出来了吗？ 
这个跨域问题怎么解决呀，可恶
![image](https://user-images.githubusercontent.com/48432322/160998957-9d571e38-304c-4757-ab33-30f77b1c86ec.png)

**Comment by windwindwa** [comment]
### 重新启动obsidian
- 没有跨域问题报错
- 以前的跳转链接有效
- **但仍自动粘贴功能仍然失效，手动复制控制台报错，其他表现正常**
![image](https://user-images.githubusercontent.com/48432322/161001319-83db1f4d-b092-4e24-a7f2-833e4a543c6a.png)

**Comment by chenghongyao** [comment]
跨域错误是正常的，插件没有用到跨域操作。

标注自动插入需要通过`ctrl+点击`，或者点击`自动插入`按钮打开自动插入新增标注的功能。
在自动插入前必须先激活一个markdown文件（点击一下对应文件的标题栏）。

![image](https://user-images.githubusercontent.com/16313317/161011749-23dd2c2f-9ef8-49b2-87b5-944460c776e7.png)

**Comment by chenghongyao** [comment]
> ### 配置与插件版本：
> mac mini M1，obsidian v0.14.2, webview是文档中提供的新版（截止2022.3.31日）https://kknwfe6755.feishu.cn/docs/doccnBfbtETItLHMmbDBGBRdPrh booknote-0.2.4-beta
> 
> ### 问题描述
> * 通过booknote打开pdf文件，控制台报错webview跨域错误。但可以使用
> * 通过高亮涂抹文字，没有自动粘贴到右侧已打开文档中，手动复制，可以使用，但控制台报错。
> 
> ### 报错截图如下：
> ![image](https://user-images.githubusercontent.com/48432322/160996563-ea87d541-21c7-4129-bae4-cec8a277b431.png)

这个错误可能是别的插件产生的，看这图无法确定。
