### ISSUE TITLE
远程服务器失效了

### ISSUE THREAD

**Issue by zijie98** [chenghongyao/obsidian-booknote-plugin#21]
远程服务器失效了，不能远程启动，在MAC电脑上，
/Users/jason/Library/Mobile Documents/iCloud~md~obsidian/Documents/Obsidian_data/.obsidian/webviewer
本地库路径用云盘不能启动

**Comment by chenghongyao** [comment]
请查看最新的[参考教程](https://chenghongyao.github.io/obsidian-bookmaster-plugin/#/QuickStart)
