### ISSUE TITLE
请问可以定义书库的文件列表排序方式么

### ISSUE THREAD

**Issue by Rightone1117** [chenghongyao/obsidian-booknote-plugin#25]
目前文件列表的排序方式好像既不是名称排序，也不是修改时间排序。
请问是否可以定义某种排序方式，方便查找文件，特别是在Advanced Book Explorer里面，无法通过文件名称进行筛选，如果书库文件比较多的话，很难找到需要打开的文件。
谢谢~！

**Comment by chenghongyao** [comment]
不知道是什么排序方式，最新版已经支持搜索文件（根据文件名或标题），请使用最新版本测试，还有问题可以重新打开issue。
