### ISSUE TITLE
pdf裁剪图片在obsidian中无法预览

### ISSUE THREAD

**Issue by randolfly** [chenghongyao/obsidian-booknote-plugin#28]
### 问题简介
在pdf中裁剪区域并在obsidian笔记中引用，其无法显示

obsidian 版本： 0.15.9
bookNote版本：0.2.4.beta
测试平台：windows10 

### 问题情况

1. 已经生成了相应的png文件
![image](https://user-images.githubusercontent.com/37769048/182513265-85832703-a0e9-4d8b-a9ce-5b14e11466f1.png)

2. 预览图如下
![image](https://user-images.githubusercontent.com/37769048/182513181-3fbb5767-2331-4921-9ac9-9bac94b45048.png)

可以发现，问题在于obsidian无法引用这种长文件名的图片`p2r42.160,642.680,302.200,739.210z2i(85eda4da-b0d0-521d-1c4b-01a14666c8d0).png`

> 已经解除了windows长文件名限制

### 解决建议

或许在`BookView.ts`中179行可以修改其生成的图片文件名命名方式？
```javascript
const imgPath = this.plugin.normalizeBooksDataPathOfVault(this.currentBook.vault, `${imgDir}/p${annoPage}r${annoRect}z${realZoom}i(${annoId}).png`);
```

需要这么长的文件名吗？

最后，作者的插件功能写得很好，十分感谢！

**Comment by chenghongyao** [comment]
是的，路径过长会导致图片无法显示，这个是ob本身的问题。路径长是为了定位图片，在之前的版本中很难解决。 

v0.3.0 中修改了文件管理方式，不会有这个问题，欢迎[测试](https://forum-zh.obsidian.md/t/topic/12333)。

**Comment by randolfly** [comment]
> 是的，路径过长会导致图片无法显示，这个是ob本身的问题。路径长是为了定位图片，在之前的版本中很难解决。
> 
> v0.3.0 中修改了文件管理方式，不会有这个问题，欢迎[测试](https://forum-zh.obsidian.md/t/topic/12333)。

好的，我会测试下的👍
