### ISSUE TITLE
选择文字没有弹出复制回链

### ISSUE THREAD

**Issue by viperbbb** [chenghongyao/obsidian-booknote-plugin#32]
选择文字没有弹出复制回链，选择注译才会弹出复制回链，复制回链可以在选小标题或者一段文字后弹出吗。。。

**Comment by chenghongyao** [comment]
回链只能定位标注

**Comment by viperbbb** [comment]
谢谢，收到。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月3日(星期一) 上午8:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenghongyao/obsidian-booknote-plugin] 选择文字没有弹出复制回链 (Issue #32)





 
回链只能定位标注
