### ISSUE TITLE
内存不会释放啊

### ISSUE THREAD

**Issue by AlexShyXie** [chenghongyao/obsidian-booknote-plugin#33]
内存不会释放啊
我反复打开关闭某个pdf，软件的内存占用会不断增加

**Comment by AlexShyXie** [comment]
求助，请问有什么办法能解决这个问题

**Comment by chenghongyao** [comment]
不好意思，没注意过这个问题，我再研究一下。

**Comment by AlexShyXie** [comment]
> 不好意思，没注意过这个问题，我再研究一下。

感谢，我试了annotator，也是这样，不知道是不是我的问题
