### ISSUE TITLE
按照官方教程安装配置， 双击pdf文件不能显示，推断是 webviewer 调用问题，不知道从哪里下手解决

### ISSUE THREAD

**Issue by MassimoQu** [chenghongyao/obsidian-booknote-plugin#34]
配置：
win10
obsidian0.15.9
obsidian-booknote-plugin-0.2.4-beta
webviewer0.2.2
（booknote 和 webviewer 版本是官方飞书文档提供的最新版本）

问题表现：
booknote 插件配置中设置完 webviewer 的本地绝对路径 和 主书库路径之后， 打开 book explorer 双击 pdf 文件，显示区标题栏显示pdf文件名，但显示区其他区域空白，不能加载pdf内容

个人思考和尝试：
1. 看起来是webviewer的问题，插件设置中关掉 使用本地服务器 选项重启再尝试：“Not Found - Request ID: 01GEV177PV3WXJ2X9WZVZ6Z9N1” 远程服务器看起来有问题；
2. 又打开 使用本地服务器 选项，把插件设置中的 本地webviewer 文件路径一栏清除 重启再尝试，结果和上面问题一样：显示区标题栏显示pdf文件名，但显示区其他区域空白，不能加载pdf内容。大概确定是 webviewer 问题。
可以确定webviewer路径正确，如E:\webviewer，该路径下就是core pdfjs ui config.js四个文件
3. obsidian 打开并保持booknote 插件打开的时候 win10 cmd netstat 看端口占用，插件默认端口1448并没有被占用，不知道插件运行的时候实际上应不应该占用。

总结：应该是 webviewer 调用问题，但是才疏学浅又不知道从哪里入手解决问题，恳请作者大大提供一下思路

**Comment by chenghongyao** [comment]
修改一下端口试试，按ctrl+shift+i 看看有没有报错。远程服务器已经没有更新了，因该是用不了了。

**Comment by NobabyCares** [comment]
win11 22hz 
obsidian 1.0.3
obsidian-booknote-plugin-0.2.4-beta
webviewer0.2.2

我把远程Webviewer远程服务内容删除,在把端口1448改成8090能成

**Comment by chenghongyao** [comment]
如果解决了那我就先关闭了

**Comment by zhangruiming1970** [comment]
我的PDF直接点击不能打开，但是用annotation插件可以打开。后来把插件obsidian-extract-pdf文件夹删除后，就正常了。
