### ISSUE TITLE
能否实现pdf ocr矫正或其他方式

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [chenghongyao/obsidian-booknote-plugin#38]
因为有时选中的部分经常有错误（扫描版的pdf）
所以能否ocr识别矫正（比如百度ocr）
如果不能，能否在选项中增加框选的两种可选配置，如果感觉扫描的挺准确，如果感觉不准确就选用这个[📌]({{url}}) 
每次需要手动感觉不舒服，谢谢了

**Comment by shoudeyunkaijianyueming** [comment]
`[📌]({{url}})`
修改上面的图标

**Comment by chenghongyao** [comment]
> 因为有时选中的部分经常有错误（扫描版的pdf） 所以能否ocr识别矫正（比如百度ocr） 如果不能，能否在选项中增加框选的两种可选配置，如果感觉扫描的挺准确，如果感觉不准确就选用这个[📌](%7B%7Burl%7D%7D) 每次需要手动感觉不舒服，谢谢了


目前没有做ocr的打算，不是目前的重点。

我不太明白最后两句是什么意思。但是回链使用多种可选模板我考虑过，以后可能会实现。

**Comment by shoudeyunkaijianyueming** [comment]
最后两句的意思是如果这个扫描搞经过abby这个的ocr处理后如果识别的比较准，我就用默认模版这样既有内容又有链接.
但是，如果不准确很多错字等等我就用我自己的模版
<img width="161" alt="image" src="https://user-images.githubusercontent.com/71814666/202381029-58813cec-9fdd-4417-8dd3-86484f65cf45.png">
所以我希望能有快速切换可选模版的选项，当然没有也没关系，现在也完全够用
