### ISSUE TITLE
Ipad、安卓端如何启用bookview?

### ISSUE THREAD

**Issue by JamaisVuu** [chenghongyao/obsidian-booknote-plugin#39]
能给点方法思路上的提示吗?

**Comment by chenghongyao** [comment]
ipad支持不了，主要是没法读外部文件夹。安卓可以(体验不是很好)，后面我再写个教程。

**Comment by chenghongyao** [comment]
最新版本支持了安卓，请看参考[教程](https://chenghongyao.github.io/obsidian-bookmaster-plugin/#/QuickStart?id=%e7%a7%bb%e5%8a%a8%e7%ab%af%e9%83%a8%e7%bd%b2%ef%bc%88%e5%ae%89%e5%8d%93%ef%bc%89)。
