### ISSUE TITLE
标注链接参数错误

### ISSUE THREAD

**Issue by Yeijon** [chenghongyao/obsidian-booknote-plugin#43]
很感谢大佬开发的插件，最近在使用过程中发现复制回链后，粘贴到ob中，再次点击回链出现弹窗“标注链接参数错误”，无法实现跳转

**Comment by chenghongyao** [comment]
更新[config.js](https://github.com/chenghongyao/obsidian-booknote-plugin/blob/master/resources/config.js)试下

**Comment by skyerGalaxy** [comment]
我也遇到了相同的问题,请问这个文件在哪里?

**Comment by chenghongyao** [comment]
> 我也遇到了相同的问题,请问这个文件在哪里?

https://github.com/chenghongyao/obsidian-booknote-plugin/blob/master/resources/config.js
