### ISSUE TITLE
0.2.4版本遇到的几个问题

### ISSUE THREAD

**Issue by YuanAaron** [chenghongyao/obsidian-booknote-plugin#45]
1、图片双击无法跳转（开发者工具无报错）
2、设置多书库后，右键图标只有主书库
3、用电脑自带的pdf阅读器打开后注释并没有保存

**Comment by chenghongyao** [comment]
请使用最新版本测试，还有问题可以重新打开issue（注意最新版本的标注图片使用ctrl+点击实现跳转）。
