### ISSUE TITLE
二次安装后无法打开文件，报错：Site Not Found

### ISSUE THREAD

**Issue by Dennifer** [chenghongyao/obsidian-booknote-plugin#46]
第一次安装后可以使用，删除后再次安装始终无法打开文件！出现以下报错，请问可以如何解决？
![image](https://user-images.githubusercontent.com/90490298/225020711-36c98ca4-f385-42db-91d6-d8bf9811460c.png)
Site Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on Netlify.
[Back to our site](https://relaxed-torvalds-5a5c77.netlify.app/)
If this is your site, and you weren't expecting a 404 for this path, please visit Netlify's ["page not found" support guide](https://answers.netlify.com/t/support-guide-i-ve-deployed-my-site-but-i-still-see-page-not-found/125?utm_source=404page&utm_campaign=community_tracking) for troubleshooting tips.

**Comment by yizhenAllen** [comment]
同样出现了这个问题，请问如何解决呀

**Comment by chenghongyao** [comment]
请使用最新版本测试，还有问题可以重新打开issue。
