### ISSUE TITLE
记忆,连续

### ISSUE THREAD

**Issue by skyerGalaxy** [chenghongyao/obsidian-booknote-plugin#47]
在使用过程中,有下面两个建议,希望作者采纳!
- 导入的PDF无法实现连续滑动
- 增加一个记忆当前阅读位置的功能,每次都重新寻找阅读位置很麻烦

**Comment by chenghongyao** [comment]
- 连续滑动页面上可以设置的，你找一下
- 3.x支持记忆了，不过还在测试

**Comment by skyerGalaxy** [comment]
> - 连续滑动页面上可以设置的，你找一下
> - 3.x支持记忆了，不过还在测试

谢谢

**Comment by skyerGalaxy** [comment]
> - 连续滑动页面上可以设置的，你找一下
> - 3.x支持记忆了，不过还在测试

- 滑动这个问题，我发现部分文件不支持(就没有连续的选项），即使它们都属于pdf类型
- 还有批注链接失效这个问题也是，部分批注文件失效，但有的文件就没有这个问题，它们同在一个文件夹下

**Comment by chenghongyao** [comment]
第一个问题没有遇到过，较大的文件会自动钱还未页模式，第二个问题应该解决了，请使用最新版本测试。

> > * 连续滑动页面上可以设置的，你找一下
> > * 3.x支持记忆了，不过还在测试
> 
> * 滑动这个问题，我发现部分文件不支持(就没有连续的选项），即使它们都属于pdf类型
> * 还有批注链接失效这个问题也是，部分批注文件失效，但有的文件就没有这个问题，它们同在一个文件夹下
