### ISSUE TITLE
点击文档中的图片，打开的booknote文件夹下的图片，而不是pdf本身截图的位置

### ISSUE THREAD

**Issue by AspieterPan** [chenghongyao/obsidian-booknote-plugin#49]
环境：MacBook Pro M1

**Comment by chenghongyao** [comment]
可能需要再设置里打开跳转功能，默认是没有打开的。

不知道你用的是哪个版本，booknote的双击跳转可能会和别的插件冲突，最新的bookmaster版本改成了ctrl+单击
