### ISSUE TITLE
复制注释回链被识别成区域摘录

### ISSUE THREAD

**Issue by kokoromanz** [chenghongyao/obsidian-booknote-plugin#50]
插件作者您好，booknote插件真的帮助我解决了很多问题，但是一直以来，当我复制注释回链时会默认识别为图片链接，想请教是否有解决办法？
<img width="601" alt="image" src="https://github.com/chenghongyao/obsidian-booknote-plugin/assets/57253184/4327f54d-7ece-45fb-a57d-025c81bbe2b7">
<img width="554" alt="image" src="https://github.com/chenghongyao/obsidian-booknote-plugin/assets/57253184/96c291f9-e406-4bba-a9be-a9b1860b954a">

**Comment by chenghongyao** [comment]
这个因为是非选文模式，所以自动识别为区域摘录了。

这是个bug，后面改下。

**Comment by chenghongyao** [comment]
最新版本已修复
