### ISSUE TITLE
作者你好，新版ob点击之后提示标注链接参数错误怎么办呀

### ISSUE THREAD

**Issue by adcemdmf** [chenghongyao/obsidian-booknote-plugin#51]
![image](https://github.com/chenghongyao/obsidian-booknote-plugin/assets/55292594/7b0abc34-168f-4408-89b8-4b2dc68add5c)

**Comment by chenghongyao** [comment]
最新的版本时什么版本？链接使用哪个版本生成的？0.3和之前的时不兼容的

**Comment by adcemdmf** [comment]
> 最新的版本时什么版本？链接使用哪个版本生成的？0.3和之前的时不兼容的

作者你好，ob是1.3.4，booknote是0.2.4。而且之前没问题可以跳转的链接会提示文件不存在，但是我书库路径没有更改文件也没有删除。
![image](https://github.com/chenghongyao/obsidian-booknote-plugin/assets/55292594/f3b83fea-1012-479b-9566-17fd8ecede3c)

**Comment by chenghongyao** [comment]
更新一下[config.js](https://github.com/chenghongyao/obsidian-booknote-plugin/blob/master/resources/config.js)文件

**Comment by adcemdmf** [comment]
> 更新一下[config.js](https://github.com/chenghongyao/obsidian-booknote-plugin/blob/master/resources/config.js)文件

请问是下载后放进插件文件夹吗？还是一样的

**Comment by chenghongyao** [comment]
> 

替换掉webviewer文件夹下的这个文件

**Comment by adcemdmf** [comment]
> > 
> 
> 替换掉webviewer文件夹下的这个文件

谢谢，新创建的链接可以跳转了，但是之前的还是显示文件不存在呢，以前的没办法用了吗

**Comment by chenghongyao** [comment]
> > > 
> > 
> > 
> > 替换掉webviewer文件夹下的这个文件
> 
> 谢谢，新创建的链接可以跳转了，但是之前的还是显示文件不存在呢，以前的没办法用了吗

是的，之前出了 bug，里面 book 参数出错了。不想重新复制链接的话，你可以把里面的book=null换成正确的参数，随便在复制一个就可以看到 `……book=xxxxxx&yy=..…`,把错误链接里的 null 换成xxxxxxx 的内容
