### ISSUE TITLE
能否麻烦写一个README，Mac下实在是没找到比较完善的教程

### ISSUE THREAD

**Issue by samwei12** [chenghongyao/obsidian-booknote-plugin#53]
目前开启了Webview服务器，能够检索到书籍，但打开的时候始终提示 `The requested URL was not found on this server.` 
麻烦作者能否抽空写个具体如何配置使用的文档，谢谢

**Comment by Anz-03** [comment]
我也是，求出一个文档

**Comment by chenghongyao** [comment]
已将出了一个初步的[文档](https://chenghongyao.github.io/obsidian-bookmaster-plugin/#/QuickStart)，因为我没有mac的测试条件，所以没法给出详细说明，寄希望于有人帮我提供了-_-，如果有问题可以重新打开issue。
