### ISSUE TITLE
在ipad中无法打开pdf文档

### ISSUE THREAD

**Issue by primejava** [chenghongyao/obsidian-booknote-plugin#56]
你好，我在电脑端可以正常使用这个插件，但是在ipad上只能打开插件的阅读窗口，但窗口空白，文件实际上是无法打开的

**Comment by chenghongyao** [comment]
没有足够的信息我无法提供任何支持。ipad上目前还没有很好的支持，主要是服务器不好搭建，另外书库地址也无法随便指定。
