### ISSUE TITLE
PDFTRON的水印能去掉吗？

### ISSUE THREAD

**Issue by Ori-Replication** [chenghongyao/obsidian-booknote-plugin#57]
使用过程中PDF上一直有个很大的PDFTRON的水印。请问这个能想办法去掉吗？
![image](https://github.com/chenghongyao/obsidian-bookmaster-plugin/assets/109295054/7cca9089-73e6-4034-b71c-687cea20720b)

**Comment by chenghongyao** [comment]
正版sdk才能去掉，正版很贵的。以后尝试用pdfjs做一个。
