### ISSUE TITLE
booknote会与ob自带pdf查看功能冲突

### ISSUE THREAD

**Issue by xjn6666** [chenghongyao/obsidian-booknote-plugin#58]
ob版本1.4.16。当启用booknote插件时，会导致md中插入的pdf附件无法查看，关闭booknote插件并重启ob后才能查看md中插入的pdf附件

**Comment by chenghongyao** [comment]
> ob版本1.4.16。当启用booknote插件时，会导致md中插入的pdf附件无法查看，关闭booknote插件并重启ob后才能查看md中插入的pdf附件

是bookmaster吧，哪个版本，我测试了最新的没有这个问题，可以提供录屏吗。

**Comment by xjn6666** [comment]
> > ob版本1.4.16。当启用booknote插件时，会导致md中插入的pdf附件无法查看，关闭booknote插件并重启ob后才能查看md中插入的pdf附件
> 
> 是bookmaster吧，哪个版本，我测试了最新的没有这个问题，可以提供录屏吗。

哦，我用的确实是booknote，一直都不知道booknote更新成bookmaster了。我是在飞书文档https://kknwfe6755.feishu.cn/docs/doccnBfbtETItLHMmbDBGBRdPrh
下面的那个链接那里跳转到这个github仓库的。
![image](https://github.com/chenghongyao/obsidian-bookmaster-plugin/assets/58368436/1d868dcf-cf84-437e-9029-f0dae6350466)
我先更新到bookmaster试试先。
谢谢佬的回复

**Comment by xjn6666** [comment]
PKM社区那里的pdf插件介绍一直还是booknote，所以我就用起了booknote
![image](https://github.com/chenghongyao/obsidian-bookmaster-plugin/assets/58368436/9d42099c-a9b7-4b59-8fd8-2b82f9894005)

**Comment by chenghongyao** [comment]
> > > ob版本1.4.16。当启用booknote插件时，会导致md中插入的pdf附件无法查看，关闭booknote插件并重启ob后才能查看md中插入的pdf附件
> > 
> > 
> > 是bookmaster吧，哪个版本，我测试了最新的没有这个问题，可以提供录屏吗。
> 
> 哦，我用的确实是booknote，一直都不知道booknote更新成bookmaster了。我是在飞书文档https://kknwfe6755.feishu.cn/docs/doccnBfbtETItLHMmbDBGBRdPrh 下面的那个链接那里跳转到这个github仓库的。 ![image](https://private-user-images.githubusercontent.com/58368436/287974673-1d868dcf-cf84-437e-9029-f0dae6350466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDA4MjUsIm5iZiI6MTcwMTg0MDUyNSwicGF0aCI6Ii81ODM2ODQzNi8yODc5NzQ2NzMtMWQ4NjhkY2YtY2Y4NC00MzdlLTkwMjktZjBkYWU2MzUwNDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA1Mjg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZGE3NTllYWQxZmI2OTQwNzQzMTc5ZjZiNzhkOTk3N2VlNjRjZWYwNGNiY2IzYjA2ZjEwNjViODQ4MTY0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B_P45B9vBJQV9vGEBXchYEJMfI0TVCnrXlJZnEgPgew) 我先更新到bookmaster试试先。 谢谢佬的回复

更新好久了，之前不行可能是带的pdfjs和最新的ob自带的冲突了，有问题可以重新打开issue.
