### ISSUE TITLE
添加booknote project功能的booknote-books的别名

### ISSUE THREAD

**Issue by YQGong** [chenghongyao/obsidian-booknote-plugin#7]
目前直接显示了pdf的文件名，但是如果文件名很长，或者文件名不方便修改的话，会导致UI混乱，可以添加一个别名的选项，方便用户自定义特定pdf的显示名称，甚至在不同booknote project中，同一个pdf可以有不同的名称，让这个功能更加整洁易用。

**Comment by chenghongyao** [comment]
设置了title属性的话会显示title
