### ISSUE TITLE
[Help] Create a Release for Using this Plugin

### ISSUE THREAD

**Issue by FelipeRearden** [chenghongyao/obsidian-booknote-plugin#9]
Hello @chenghongyao !!!!

Forgive for my question, could you create a release to make easier for us to use this plug-in? 🙏 

A community friend commented about this plugin on Discord and I wanted to take a look :)

---

Thank you very much for reading this!

I wish you a fantastic day!

**Comment by chenghongyao** [comment]
Sorry for the inconvenience, but this plugin is currently unstable. There are also some copyright issues, and the English version is not supported yet. Most importantly, I'm quite busy these day, so the whole progress will be delay for months.

**Comment by FelipeRearden** [comment]
> Sorry for the inconvenience, but this plugin is currently unstable.
> 
> 
> 
> There are also some copyright issues, and the English version is not supported yet. Most importantly, I'm quite busy these day, so the whole progress will be delayed for months.
> 
> 

Thanks for your reply!

I understand :) 

Maybe some day in the future I get a chance to use your plugin. Looks an amazing plugin :)

I wish you the best!
